# Generated by Django 6.1 on 2026-09-12 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akreditasi', '0003_alter_unitkerja_options_unitkerja_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (Developer / IT RS)'), ('ADMIN_RS', 'Admin Akreditasi RS (Tim Mutu)'), ('KOORDINATOR_POKJA', 'Koordinator Pokja (Ketua Kelompok Kerja)'), ('KEPALA_UNIT', 'Kepala Unit Kerja'), ('ASESOR', 'Asesor / Viewer (Baca Saja)')], default='ASESOR', max_length=30, verbose_name='Peran / Hak Akses')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Nama Lengkap')),
                ('jabatan', models.CharField(blank=True, max_length=150, verbose_name='Jabatan')),
                ('telepon', models.CharField(blank=True, max_length=30, verbose_name='Nomor Telepon')),
                ('photo_url', models.URLField(blank=True, verbose_name='URL Foto Profil')),
                ('is_active_member', models.BooleanField(default=True, verbose_name='Anggota Tim Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pokja_access', models.ManyToManyField(blank=True, help_text='Daftar Pokja yang dapat dikelola oleh Koordinator Pokja ini.', to='akreditasi.category', verbose_name='Akses Pokja (Koordinator Pokja)')),
                ('unit_kerja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='akreditasi.unitkerja', verbose_name='Unit Kerja Terkait')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Akun Pengguna')),
            ],
            options={
                'verbose_name': 'Profil Pengguna',
                'verbose_name_plural': 'Profil Pengguna',
                'ordering': ['role', 'user__username'],
            },
        ),
    ]
