# Generated by Django 6.1.1 on 2026-09-24 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nip_nrp',
            field=models.CharField(blank=True, help_text='Nomor Induk Pegawai / Nomor Registrasi Pegawai.', max_length=30, verbose_name='NIP / NRP / No. Pegawai'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profesi',
            field=models.CharField(blank=True, choices=[('', '— Pilih Profesi —'), ('DOKTER_SPESIALIS', 'Dokter Spesialis'), ('DOKTER_UMUM', 'Dokter Umum'), ('PERAWAT', 'Perawat'), ('BIDAN', 'Bidan'), ('APOTEKER', 'Apoteker'), ('TTK', 'Tenaga Teknis Kefarmasian'), ('ANALIS_LAB', 'Pranata Laboratorium Medik'), ('RADIOGRAFER', 'Radiografer'), ('NUTRISIONIS', 'Nutrisionis / Dietisien'), ('FISIOTERAPIS', 'Fisioterapis'), ('PEREKAM_MEDIS', 'Perekam Medis & Informasi Kesehatan'), ('LAINNYA', 'Tenaga Kesehatan Lainnya')], default='', help_text='Wajib diisi untuk role Staf Nakes.', max_length=30, verbose_name='Profesi Klinis'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (Developer / IT RS)'), ('ADMIN_RS', 'Admin Akreditasi RS (Tim Mutu)'), ('KOORDINATOR_POKJA', 'Koordinator Pokja (Ketua Kelompok Kerja)'), ('KEPALA_UNIT', 'Kepala Unit Kerja'), ('STAF_NAKES', 'Staf Nakes / Pelaksana Unit'), ('ASESOR', 'Asesor / Viewer (Baca Saja)')], default='ASESOR', max_length=30, verbose_name='Peran / Hak Akses'),
        ),
        migrations.CreateModel(
            name='NakesCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('STR', 'Surat Tanda Registrasi (STR)'), ('SIP', 'Surat Izin Praktik (SIP)'), ('SPK_RKK', 'Surat Penugasan Klinis & RKK'), ('PELATIHAN_BHD', 'Pelatihan BHD / BLS (KPS 8)'), ('PELATIHAN_PPI', 'Pelatihan PPI Dasar (PPI/KPS)'), ('PELATIHAN_PMKP', 'Pelatihan Mutu & Keselamatan Pasien'), ('PELATIHAN_K3RS', 'Pelatihan K3RS & APAR/Disaster'), ('PELATIHAN_LAIN', 'Sertifikat Kompetensi Khusus')], max_length=20, verbose_name='Jenis Dokumen')),
                ('title', models.CharField(max_length=250, verbose_name='Nama / Judul Dokumen')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Nomor Dokumen/Sertifikat')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Terbit / Pelaksanaan')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Masa Berlaku Sampai')),
                ('file_url', models.URLField(blank=True, max_length=500, verbose_name='URL Dokumen (Cloud/Supabase)')),
                ('file', models.FileField(blank=True, null=True, upload_to='kps/%Y/%m/', verbose_name='Berkas Scan')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Verifikasi'), ('VERIFIED', 'Terverifikasi Tim Mutu/KPS'), ('REJECTED', 'Ditolak / Perlu Perbaikan'), ('EXPIRED', 'Kedaluwarsa')], default='PENDING', max_length=20, verbose_name='Status Verifikasi')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Catatan Verifikator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='accounts.userprofile', verbose_name='Pemilik Dokumen')),
            ],
            options={
                'verbose_name': 'Kredensial Nakes (KPS)',
                'verbose_name_plural': 'Kredensial Nakes (KPS)',
                'ordering': ['doc_type', '-created_at'],
            },
        ),
    ]
