# Generated by Django 5.2.17 on 2026-09-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_nip_nrp_userprofile_profesi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (Developer / IT RS)'), ('ADMIN_RS', 'Admin Akreditasi RS (Tim Mutu)'), ('KOORDINATOR_POKJA', 'Koordinator Pokja (Ketua Kelompok Kerja)'), ('KEPALA_UNIT', 'Kepala Unit Kerja'), ('STAF_NAKES', 'Staf Nakes / Pelaksana Unit'), ('ASESOR', 'Asesor / Viewer (Baca Saja)')], max_length=30, unique=True, verbose_name='Peran Pengguna')),
                ('can_view_pdca', models.BooleanField(default=True, verbose_name='Lihat Matriks PDCA')),
                ('can_edit_pdca', models.BooleanField(default=False, verbose_name='Edit Plan/Do/Check/Action')),
                ('can_score_ep', models.BooleanField(default=False, verbose_name='Beri Skor EP (0/5/10)')),
                ('can_view_rdwos', models.BooleanField(default=True, verbose_name='Akses Dokumen RDWOS')),
                ('can_upload_rdwos', models.BooleanField(default=False, verbose_name='Unggah Dokumen Bukti')),
                ('can_delete_rdwos', models.BooleanField(default=False, verbose_name='Hapus Dokumen Bukti')),
                ('can_view_risiko', models.BooleanField(default=True, verbose_name='Lihat Register Risiko')),
                ('can_manage_risiko', models.BooleanField(default=False, verbose_name='Input & Evaluasi Risiko')),
                ('can_lapor_insiden', models.BooleanField(default=True, verbose_name='Melaporkan Insiden (KNC/KTD)')),
                ('can_investigate_insiden', models.BooleanField(default=False, verbose_name='Investigasi & Analisis Insiden')),
                ('can_view_scoring', models.BooleanField(default=True, verbose_name='Lihat Auto-Scoring KARS')),
                ('can_export_reports', models.BooleanField(default=False, verbose_name='Cetak Dokumen & Ekspor Excel')),
                ('can_manage_units', models.BooleanField(default=False, verbose_name='Kelola Struktur Unit Kerja')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Kelola Pengguna & Hak Akses')),
                ('can_verify_kps', models.BooleanField(default=False, verbose_name='Verifikasi Kredensial Nakes')),
                ('can_view_audit_log', models.BooleanField(default=False, verbose_name='Lihat Log Audit Sistem')),
                ('can_access_control_center', models.BooleanField(default=False, verbose_name='Akses Menu Pusat Kontrol Admin')),
                ('can_manage_system_settings', models.BooleanField(default=False, verbose_name='Ubah Konfigurasi Sistem (Ambang Batas, Tema, Freeze)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi Izin Peran',
                'verbose_name_plural': 'Konfigurasi Izin Peran',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Hak Akses Kustom'),
        ),
    ]
