# Generated by Django 5.2.17 on 2026-10-02 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bed', models.CharField(max_length=20, verbose_name='Kode Bed')),
                ('status', models.CharField(choices=[('TERSEDIA', 'Tersedia'), ('TERISI', 'Terisi'), ('STERILISASI', 'Proses Sterilisasi'), ('TIDAK_AKTIF', 'Tidak Aktif')], default='TERSEDIA', max_length=15, verbose_name='Status')),
                ('catatan', models.CharField(blank=True, max_length=200, verbose_name='Catatan')),
            ],
            options={
                'verbose_name': 'Bed',
                'verbose_name_plural': 'Bed Management',
                'ordering': ['ruangan', 'kode_bed'],
            },
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rm', models.CharField(max_length=20, unique=True, verbose_name='No. Rekam Medis')),
                ('nik', models.CharField(blank=True, max_length=16, verbose_name='NIK')),
                ('nama_lengkap', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('golongan_darah', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('-', 'Tidak Diketahui')], default='-', max_length=3, verbose_name='Golongan Darah')),
                ('alamat', models.TextField(blank=True, verbose_name='Alamat')),
                ('no_hp', models.CharField(blank=True, max_length=20, verbose_name='No. HP')),
                ('no_bpjs', models.CharField(blank=True, max_length=20, verbose_name='No. BPJS')),
                ('alergi_obat', models.TextField(blank=True, help_text='Pisahkan dengan koma', verbose_name='Alergi Obat')),
                ('alergi_lain', models.TextField(blank=True, verbose_name='Alergi Lain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pasien',
                'verbose_name_plural': 'Data Pasien',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Ruangan')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Ruangan')),
                ('kelas', models.CharField(choices=[('VIP', 'VIP'), ('1', 'Kelas I'), ('2', 'Kelas II'), ('3', 'Kelas III'), ('ICU', 'ICU'), ('IGD', 'IGD'), ('OK', 'Kamar Operasi')], max_length=5, verbose_name='Kelas')),
                ('jenis', models.CharField(choices=[('RANAP', 'Rawat Inap'), ('IGD', 'IGD'), ('RAJAL', 'Rawat Jalan'), ('OK', 'Kamar Operasi'), ('ICU', 'ICU')], default='RANAP', max_length=10, verbose_name='Jenis')),
                ('kapasitas', models.IntegerField(default=1, verbose_name='Kapasitas Bed')),
            ],
            options={
                'verbose_name': 'Ruangan',
                'verbose_name_plural': 'Ruangan',
                'ordering': ['kelas', 'kode'],
            },
        ),
        migrations.CreateModel(
            name='KunjunganPasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kunjungan', models.CharField(max_length=30, unique=True, verbose_name='No. Kunjungan')),
                ('jenis_kunjungan', models.CharField(choices=[('IGD', 'Gawat Darurat (IGD)'), ('RAJAL', 'Rawat Jalan (Poliklinik)'), ('RANAP', 'Rawat Inap')], max_length=10, verbose_name='Jenis Kunjungan')),
                ('tanggal_masuk', models.DateTimeField(verbose_name='Tanggal Masuk')),
                ('tanggal_keluar', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Keluar')),
                ('dpjp', models.CharField(blank=True, max_length=150, verbose_name='DPJP')),
                ('poliklinik', models.CharField(blank=True, max_length=100, verbose_name='Poliklinik / Unit')),
                ('penjamin', models.CharField(choices=[('UMUM', 'Umum / Tunai'), ('BPJS', 'BPJS Kesehatan'), ('ASURANSI', 'Asuransi Swasta')], default='UMUM', max_length=10, verbose_name='Penjamin')),
                ('diagnosa_masuk', models.CharField(blank=True, max_length=300, verbose_name='Diagnosa Masuk (ICD-10)')),
                ('diagnosa_keluar', models.CharField(blank=True, max_length=300, verbose_name='Diagnosa Keluar (ICD-10)')),
                ('triage', models.CharField(blank=True, choices=[('MERAH', 'Merah — Prioritas I (Kritis)'), ('KUNING', 'Kuning — Prioritas II (Urgent)'), ('HIJAU', 'Hijau — Prioritas III (Non-Urgent)'), ('HITAM', 'Hitam — Prioritas IV (Expectant)')], max_length=10, verbose_name='Triage IGD')),
                ('status', models.CharField(choices=[('DAFTAR', 'Terdaftar'), ('TRIAGE', 'Triage (IGD)'), ('ASESMEN', 'Asesmen PPA'), ('RANAP', 'Rawat Inap'), ('PULANG', 'Pulang'), ('RUJUK', 'Dirujuk Keluar'), ('MENINGGAL', 'Meninggal')], default='DAFTAR', max_length=15, verbose_name='Status Kunjungan')),
                ('catatan_admisi', models.TextField(blank=True, verbose_name='Catatan Admisi')),
                ('general_consent', models.BooleanField(default=False, verbose_name='General Consent Ditandatangani')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kunjungan', to='pasien.bed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan', to='pasien.pasien')),
            ],
            options={
                'verbose_name': 'Kunjungan Pasien',
                'verbose_name_plural': 'Kunjungan Pasien',
                'ordering': ['-tanggal_masuk'],
            },
        ),
        migrations.CreateModel(
            name='DischargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_discharge', models.DateTimeField(verbose_name='Tanggal Discharge')),
                ('kondisi_pulang', models.CharField(choices=[('MEMBAIK', 'Kondisi Membaik'), ('SEMBUH', 'Sembuh'), ('APS', 'Atas Permintaan Sendiri (APS)'), ('RUJUK', 'Dirujuk ke RS Lain'), ('MENINGGAL', 'Meninggal')], max_length=15, verbose_name='Kondisi Saat Pulang')),
                ('resume_medis', models.TextField(verbose_name='Resume Medis (Discharge Summary)')),
                ('edukasi_pulang', models.TextField(blank=True, verbose_name='Edukasi & Instruksi Pulang')),
                ('obat_pulang', models.TextField(blank=True, verbose_name='Obat Pulang')),
                ('jadwal_kontrol', models.DateField(blank=True, null=True, verbose_name='Jadwal Kontrol Ulang')),
                ('total_tagihan', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Tagihan (Rp)')),
                ('status_clearance', models.CharField(choices=[('PROSES', 'Proses Verifikasi'), ('CLEARANCE', 'Clearance / Bebas Administrasi')], default='PROSES', max_length=15, verbose_name='Status Clearance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kunjungan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='pasien.kunjunganpasien')),
            ],
            options={
                'verbose_name': 'Discharge Record',
                'verbose_name_plural': 'Discharge Records',
            },
        ),
        migrations.CreateModel(
            name='CPPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesi', models.CharField(choices=[('DOKTER', 'Dokter / DPJP'), ('PERAWAT', 'Perawat'), ('FARMASI', 'Farmasi / Apoteker'), ('GIZI', 'Gizi / Dietisien'), ('REHAB', 'Rehabilitasi Medik'), ('BIDAN', 'Bidan'), ('LAINNYA', 'PPA Lainnya')], max_length=10, verbose_name='Profesi PPA')),
                ('nama_ppa', models.CharField(max_length=150, verbose_name='Nama PPA')),
                ('tanggal', models.DateTimeField(verbose_name='Tanggal & Jam')),
                ('subjektif', models.TextField(verbose_name='S — Subjektif (Keluhan)')),
                ('objektif', models.TextField(verbose_name='O — Objektif (Pemeriksaan)')),
                ('asesmen', models.TextField(verbose_name='A — Asesmen (Diagnosa)')),
                ('plan', models.TextField(verbose_name='P — Plan (Rencana)')),
                ('verifikasi_dpjp', models.BooleanField(default=False, verbose_name='Terverifikasi DPJP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cppt', to='pasien.kunjunganpasien')),
            ],
            options={
                'verbose_name': 'CPPT',
                'verbose_name_plural': 'CPPT (Catatan Perkembangan Pasien)',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('JASA_MEDIS', 'Jasa Medis / Tindakan'), ('OBAT', 'Obat & BMHP'), ('LAB', 'Laboratorium'), ('RADIOLOGI', 'Radiologi / Imaging'), ('KAMAR', 'Biaya Kamar / Akomodasi'), ('ADMIN', 'Administrasi'), ('LAINNYA', 'Lainnya')], max_length=15, verbose_name='Kategori')),
                ('nama_item', models.CharField(max_length=200, verbose_name='Nama Item')),
                ('kuantitas', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Kuantitas')),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Satuan (Rp)')),
                ('kode_icd', models.CharField(blank=True, max_length=20, verbose_name='Kode ICD-10/9-CM')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal')),
                ('dicatat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='pasien.kunjunganpasien')),
            ],
            options={
                'verbose_name': 'Billing Item',
                'verbose_name_plural': 'Billing Pasien',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='AsesmenRisikoKlinis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('JATUH_MORSE', 'Risiko Jatuh — Morse Fall Scale (Dewasa)'), ('JATUH_HUMPTY', 'Risiko Jatuh — Humpty Dumpty (Anak)'), ('NYERI', 'Asesmen Nyeri (NRS/VAS)'), ('NUTRISI', 'Asesmen Nutrisi (MNA/NRS-2002)'), ('PPI', 'Pencegahan Infeksi (PPI Bundle)'), ('ALERGI', 'Asesmen Alergi')], max_length=20, verbose_name='Jenis Asesmen')),
                ('skor', models.IntegerField(default=0, verbose_name='Skor')),
                ('grade', models.CharField(blank=True, choices=[('RENDAH', 'Rendah'), ('SEDANG', 'Sedang'), ('TINGGI', 'Tinggi'), ('SANGAT_TINGGI', 'Sangat Tinggi')], max_length=15, verbose_name='Grade Risiko')),
                ('temuan', models.TextField(blank=True, verbose_name='Temuan / Detail Asesmen')),
                ('intervensi', models.TextField(blank=True, verbose_name='Intervensi yang Dilakukan')),
                ('dinilai_oleh', models.CharField(blank=True, max_length=150, verbose_name='Dinilai Oleh')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Asesmen')),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesmen_risiko', to='pasien.kunjunganpasien')),
            ],
            options={
                'verbose_name': 'Asesmen Risiko Klinis',
                'verbose_name_plural': 'Asesmen Risiko Klinis',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='ruangan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='pasien.ruangan'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ruangan', 'kode_bed')},
        ),
    ]
