# Generated by Django 5.2.17 on 2026-10-04 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0002_kunjunganpasien_discharge_planning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kunjunganpasien',
            name='satusehat_encounter_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SatuSehat Encounter ID'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='satusehat_status',
            field=models.CharField(choices=[('NOT_SYNCED', 'Belum Disinkronkan'), ('SYNCED', 'Tersinkronisasi'), ('FAILED', 'Gagal Sync')], default='NOT_SYNCED', max_length=15, verbose_name='Status Sync SatuSehat'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='satusehat_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SatuSehat Patient ID'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='satusehat_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Sync SatuSehat'),
        ),
        migrations.CreateModel(
            name='ResepElektronik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_resep', models.CharField(max_length=30, unique=True, verbose_name='No. Resep')),
                ('tanggal_resep', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat')),
                ('jenis_resep', models.CharField(choices=[('RAWAT_INAP', 'Rawat Inap (Depo Ranap)'), ('RAWAT_JALAN', 'Rawat Jalan (Depo Rajal)'), ('IGD', 'IGD Cito'), ('PULANG', 'Obat Pulang / Discharge')], default='RAWAT_INAP', max_length=15, verbose_name='Jenis Resep')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Dokter'), ('DIKIRIM', 'Terkirim ke Farmasi'), ('DISPENSING', 'Sedang Diracik / Dispensing'), ('SELESAI', 'Selesai & Diserahkan'), ('BATAL', 'Dibatalkan')], default='DIKIRIM', max_length=15, verbose_name='Status Farmasi')),
                ('catatan_dokter', models.CharField(blank=True, max_length=250, verbose_name='Catatan Dokter / Iter')),
                ('catatan_apoteker', models.CharField(blank=True, max_length=250, verbose_name='Catatan / Telaah Apoteker')),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai Penyerahan')),
                ('apoteker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resep_diproses', to=settings.AUTH_USER_MODEL)),
                ('dokter_peresep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resep_dibuat', to=settings.AUTH_USER_MODEL)),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resep_list', to='pasien.kunjunganpasien')),
            ],
            options={
                'verbose_name': 'Resep Elektronik',
                'verbose_name_plural': 'Resep Elektronik (Farmasi)',
                'ordering': ['-tanggal_resep'],
            },
        ),
        migrations.CreateModel(
            name='ResepDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=150, verbose_name='Nama Obat / Alkes')),
                ('bentuk_sediaan', models.CharField(choices=[('TABLET', 'Tablet / Kaplet'), ('KAPSUL', 'Kapsul'), ('SIRUP', 'Sirup / Suspensi'), ('INJEKSI', 'Injeksi / Ampul / Vial'), ('INFUS', 'Cairan Infus'), ('SALEP', 'Salep / Krim / Tetes'), ('PUYER', 'Puyer / Racikan')], default='TABLET', max_length=10, verbose_name='Bentuk')),
                ('dosis', models.CharField(help_text='Contoh: 500 mg, 1 gr, 100 ml', max_length=50, verbose_name='Dosis')),
                ('aturan_pakai', models.CharField(help_text='Contoh: 3x1 tablet sesudah makan', max_length=100, verbose_name='Signa / Aturan Pakai')),
                ('jumlah', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Satuan (Rp)')),
                ('catatan_khusus', models.CharField(blank=True, max_length=150, verbose_name='Catatan Khusus (Sebelum/Sesudah Makan, dll)')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pasien.resepelektronik')),
            ],
            options={
                'verbose_name': 'Detail Obat Resep',
                'verbose_name_plural': 'Detail Obat Resep',
            },
        ),
    ]
