# Generated by Django 6.1.1 on 2026-10-04 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0003_eprescribing_satusehat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargerecord',
            name='paps_alasan',
            field=models.TextField(blank=True, verbose_name='Alasan PAPS'),
        ),
        migrations.AddField(
            model_name='dischargerecord',
            name='paps_nama_penolak',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nama Pasien / Keluarga Penolak'),
        ),
        migrations.AddField(
            model_name='dischargerecord',
            name='skdp_diagnosa',
            field=models.CharField(blank=True, max_length=250, verbose_name='Diagnosa SKDP'),
        ),
        migrations.AddField(
            model_name='dischargerecord',
            name='skdp_nomor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nomor SKDP'),
        ),
        migrations.AddField(
            model_name='dischargerecord',
            name='skdp_terapi',
            field=models.TextField(blank=True, verbose_name='Rencana Terapi Lanjutan'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='flag_khusus',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('AMBULANS', 'Rujukan Ambulans'), ('KRITIS', 'Kondisi Kritis / Resusitasi')], default='NORMAL', max_length=10, verbose_name='Flag Kondisi Khusus'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='icd9_tindakan',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tindakan Medis (ICD-9-CM)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='konsul_catatan',
            field=models.TextField(blank=True, verbose_name='Catatan Konsultasi Internal'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='konsul_ke_poli',
            field=models.CharField(blank=True, max_length=100, verbose_name='Konsul ke Poliklinik'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='nomor_antrean',
            field=models.CharField(blank=True, max_length=25, verbose_name='No. Antrean'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='penyebab_kematian',
            field=models.TextField(blank=True, verbose_name='Penyebab Kematian'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='sisrute_alasan',
            field=models.TextField(blank=True, verbose_name='Alasan Rujukan Eksternal'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='sisrute_rs_tujuan',
            field=models.CharField(blank=True, max_length=200, verbose_name='RS Tujuan Rujukan (SISRUTE)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='status_antrean',
            field=models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DIPANGGIL', 'Dipanggil'), ('SEDANG_DILAYANI', 'Sedang Dilayani'), ('SELESAI', 'Selesai')], default='MENUNGGU', max_length=20, verbose_name='Status Antrean'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='ttv_diastole',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tekanan Darah Diastole (mmHg)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='ttv_nadi',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nadi (bpm)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='ttv_rr',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Laju Napas / RR (x/menit)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='ttv_sistole',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tekanan Darah Sistole (mmHg)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='ttv_spo2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SpO2 (%)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='ttv_suhu',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Suhu (°C)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='waktu_kematian',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Kematian'),
        ),
        migrations.CreateModel(
            name='OrderPenunjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('LAB', 'Laboratorium'), ('RADIOLOGI', 'Radiologi / Imaging')], max_length=15, verbose_name='Jenis Penunjang')),
                ('nama_pemeriksaan', models.CharField(max_length=255, verbose_name='Nama Pemeriksaan / Tindakan')),
                ('catatan_klinis', models.TextField(blank=True, verbose_name='Catatan Klinis / Indikasi')),
                ('prioritas', models.CharField(choices=[('CITO', 'CITO / Segera'), ('RUTIN', 'Rutin')], default='RUTIN', max_length=10, verbose_name='Prioritas')),
                ('status', models.CharField(choices=[('ORDERED', 'Terkirim'), ('PROSES', 'Dalam Pemeriksaan'), ('SELESAI', 'Selesai / Hasil Tersedia')], default='ORDERED', max_length=15, verbose_name='Status Order')),
                ('dokter_pengirim', models.CharField(blank=True, max_length=150, verbose_name='Dokter Pengirim')),
                ('hasil_pemeriksaan', models.TextField(blank=True, verbose_name='Hasil Pemeriksaan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_penunjang', to='pasien.kunjunganpasien')),
            ],
            options={
                'verbose_name': 'Order Penunjang',
                'verbose_name_plural': 'Order Penunjang (Lab / Radiologi)',
                'ordering': ['-created_at'],
            },
        ),
    ]
