# Generated by Django 6.1.1 on 2026-10-04 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0004_patient_management_flow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('TERSEDIA', 'Tersedia'), ('DIBOOKING', 'Dibooking / Dipesan'), ('TERISI', 'Terisi'), ('STERILISASI', 'Proses Sterilisasi'), ('TIDAK_AKTIF', 'Tidak Aktif')], default='TERSEDIA', max_length=15, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='BookingKamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_booking', models.CharField(max_length=30, unique=True, verbose_name='Nomor Booking')),
                ('waktu_booking', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pesan')),
                ('batas_waktu', models.DateTimeField(verbose_name='Batas Waktu Tunggu')),
                ('status', models.CharField(choices=[('BOOKED', 'Dipesan (Menunggu Check-in)'), ('CHECKIN', 'Sudah Masuk Kamar'), ('BATAL', 'Dibatalkan'), ('EXPIRED', 'Kedaluwarsa')], default='BOOKED', max_length=15, verbose_name='Status Booking')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan / Indikasi')),
                ('alasan_batal', models.TextField(blank=True, verbose_name='Alasan Pembatalan')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pasien.bed')),
                ('kunjungan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings', to='pasien.kunjunganpasien')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='pasien.pasien')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pemesanan Kamar (Booking Bed)',
                'verbose_name_plural': 'Pemesanan Kamar (Booking Bed)',
                'ordering': ['-waktu_booking'],
            },
        ),
    ]
