# Generated by Django 6.1.1 on 2026-10-04 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0005_bed_booking_and_general_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kunjunganpasien',
            name='ttv_gcs',
            field=models.CharField(blank=True, help_text='Contoh: E4V5M6 (15) atau Somnolen', max_length=30, verbose_name='Glasgow Coma Scale (GCS)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='ttv_skala_nyeri',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0 (Tidak Nyeri) s.d 10 (Sangat Hebat)', null=True, verbose_name='Skala Nyeri (NRS 0-10)'),
        ),
        migrations.AddField(
            model_name='orderpenunjang',
            name='critical_value_catatan',
            field=models.CharField(blank=True, max_length=200, verbose_name='Catatan Nilai Kritis'),
        ),
        migrations.AddField(
            model_name='orderpenunjang',
            name='is_critical_value',
            field=models.BooleanField(default=False, verbose_name='Critical Value Alert'),
        ),
        migrations.CreateModel(
            name='GeneralConsentRawatInap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pj', models.CharField(max_length=150, verbose_name='Nama Penanggung Jawab / Wali')),
                ('nik_pj', models.CharField(max_length=20, verbose_name='NIK Penanggung Jawab')),
                ('hubungan', models.CharField(choices=[('DIRI_SENDIRI', 'Diri Sendiri (Pasien)'), ('SUAMI_ISTRI', 'Suami / Istri'), ('ORANG_TUA', 'Orang Tua / Ayah / Ibu'), ('ANAK', 'Anak Kandung'), ('SAUDARA', 'Saudara Kandung'), ('WALI', 'Wali / Penanggung Jawab Lainnya')], max_length=20, verbose_name='Hubungan dengan Pasien')),
                ('telepon_pj', models.CharField(max_length=25, verbose_name='Nomor Telepon / WhatsApp')),
                ('alamat_pj', models.TextField(verbose_name='Alamat Lengkap')),
                ('setuju_perawatan_umum', models.BooleanField(default=True, verbose_name='Persetujuan Tindakan & Perawatan Medis Umum')),
                ('setuju_pelepasan_informasi', models.BooleanField(default=True, verbose_name='Persetujuan Pelepasan Informasi Medis & Privasi')),
                ('setuju_tata_tertib', models.BooleanField(default=True, verbose_name='Persetujuan Tata Tertib Rawat Inap & Jam Besuk')),
                ('nama_anggota_akses_info', models.TextField(blank=True, help_text='Daftar nama keluarga yang diperbolehkan menerima informasi perkembangan medis pasien.', verbose_name='Nama Anggota Keluarga yang Diberi Akses Informasi')),
                ('jaminan_biaya', models.CharField(choices=[('BPJS', 'BPJS Kesehatan / KIS'), ('UMUM', 'Biaya Pribadi (Umum / Tunai)'), ('ASURANSI', 'Asuransi Swasta / Perusahaan')], default='BPJS', max_length=15, verbose_name='Penjamin / Penanggung Biaya')),
                ('pernyataan_selisih_biaya', models.BooleanField(default=True, verbose_name='Setuju Ketentuan Selisih Biaya (Bila Naik Kelas)')),
                ('waktu_persetujuan', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Persetujuan')),
                ('kunjungan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_consent_doc', to='pasien.kunjunganpasien')),
                ('petugas_saksi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General Consent Rawat Inap',
                'verbose_name_plural': 'General Consent Rawat Inap',
            },
        ),
    ]
