# Generated by Django 6.1.1 on 2026-10-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0006_general_consent_and_advanced_clinical'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunjunganpasien',
            name='anamnesis_obat',
            field=models.TextField(blank=True, verbose_name='Riwayat Pengobatan / Obat Saat Ini'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='anamnesis_rpd',
            field=models.TextField(blank=True, verbose_name='Riwayat Penyakit Dahulu (RPD)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='anamnesis_rpk',
            field=models.TextField(blank=True, verbose_name='Riwayat Penyakit Keluarga (RPK)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='anamnesis_rps',
            field=models.TextField(blank=True, verbose_name='Riwayat Penyakit Sekarang (RPS)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='diagnosa_keperawatan_sdki',
            field=models.TextField(blank=True, help_text='Contoh: D.0077 - Nyeri Akut', verbose_name='Diagnosis Keperawatan (SDKI)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='fisik_airway',
            field=models.TextField(blank=True, verbose_name='Airway Assessment'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='fisik_breathing',
            field=models.TextField(blank=True, verbose_name='Breathing Assessment'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='fisik_circulation',
            field=models.TextField(blank=True, verbose_name='Circulation Assessment'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='fisik_disability',
            field=models.TextField(blank=True, verbose_name='Disability Assessment (Neuro)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='fisik_exposure',
            field=models.TextField(blank=True, verbose_name='Exposure / Environmental'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='intervensi_keperawatan_siki',
            field=models.TextField(blank=True, help_text='Contoh: I.08238 - Manajemen Nyeri', verbose_name='Intervensi Keperawatan (SIKI)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='luaran_keperawatan_slki',
            field=models.TextField(blank=True, help_text='Contoh: L.08066 - Tingkat Nyeri Menurun', verbose_name='Luaran Keperawatan (SLKI)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='skrining_gizi_mst',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Skor Skrining Gizi (MST)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='skrining_jatuh_grade',
            field=models.CharField(blank=True, help_text='RENDAH / SEDANG / TINGGI', max_length=20, verbose_name='Grade Risiko Jatuh'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='skrining_jatuh_skor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Skor Risiko Jatuh'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='status_psikososial',
            field=models.TextField(blank=True, verbose_name='Status Psikologis & Sosial-Ekonomi'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='status_spiritual',
            field=models.TextField(blank=True, verbose_name='Status Spiritual & Budaya'),
        ),
        migrations.AlterField(
            model_name='kunjunganpasien',
            name='status',
            field=models.CharField(choices=[('DAFTAR', 'Terdaftar'), ('TRIAGE', 'Triage (IGD)'), ('ASESMEN', 'Asesmen PPA'), ('RANAP', 'Rawat Inap'), ('PULANG', 'Pulang'), ('RUJUK', 'Dirujuk Keluar'), ('MENINGGAL', 'Meninggal'), ('BATAL', 'Dibatalkan')], default='DAFTAR', max_length=15, verbose_name='Status Kunjungan'),
        ),
    ]
