# Generated by Django 6.1.1 on 2026-10-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0007_kunjunganpasien_anamnesis_obat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunjunganpasien',
            name='fisik_head_to_toe',
            field=models.JSONField(blank=True, default=dict, verbose_name='Pemeriksaan Fisik Head-To-Toe (Standar 3.09)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='fungsional_adl',
            field=models.CharField(blank=True, help_text='Mandiri / Bantuan Parsial / Ketergantungan Total', max_length=50, verbose_name='Aktivitas Sehari-hari (ADL)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='keadaan_umum',
            field=models.CharField(blank=True, help_text='Baik / Sedang / Lemah / Buruk', max_length=30, verbose_name='Keadaan Umum'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='kesadaran',
            field=models.CharField(blank=True, help_text='Compos Mentis / Apatis / Somnolen / Sopor / Koma', max_length=30, verbose_name='Tingkat Kesadaran'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='nyeri_karakteristik',
            field=models.CharField(blank=True, help_text='Tumpul / Tajam/Tusuk / Terbakar / Denyut / Hilang-Timbul', max_length=50, verbose_name='Karakteristik Nyeri'),
        ),
    ]
