# Generated by Django 6.1.1 on 2026-10-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0008_kunjunganpasien_fisik_head_to_toe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='agama',
            field=models.CharField(blank=True, choices=[('ISLAM', 'Islam'), ('KRISTEN', 'Kristen'), ('KATOLIK', 'Katolik'), ('HINDU', 'Hindu'), ('BUDDHA', 'Buddha'), ('KONGHUCU', 'Konghucu'), ('LAINNYA', 'Lainnya')], max_length=20, verbose_name='Agama'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='alamat_pj',
            field=models.TextField(blank=True, verbose_name='Alamat Penanggung Jawab'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='hubungan_pj',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hubungan dengan Pasien'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kelurahan / Desa'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='kota_kabupaten',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kota / Kabupaten'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='nama_pj',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nama Penanggung Jawab'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='no_hp_pj',
            field=models.CharField(blank=True, max_length=30, verbose_name='No. HP / WA Penanggung Jawab'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pekerjaan'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, choices=[('SD_SMP_SMA', 'SD / SMP / SMA'), ('D3_D4', 'D3 / D4'), ('S1_S2_S3', 'S1 / S2 / S3'), ('LAINNYA', 'Lainnya')], max_length=30, verbose_name='Pendidikan Terakhir'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='rt_rw',
            field=models.CharField(blank=True, max_length=20, verbose_name='RT / RW'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='status_perkawinan',
            field=models.CharField(blank=True, choices=[('BELUM_MENIKAH', 'Belum Menikah'), ('MENIKAH', 'Menikah'), ('DUDA_JANDA', 'Duda / Janda')], max_length=20, verbose_name='Status Perkawinan'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='alamat',
            field=models.TextField(blank=True, verbose_name='Alamat Domisili Lengkap'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='no_bpjs',
            field=models.CharField(blank=True, max_length=30, verbose_name='No. BPJS'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='no_hp',
            field=models.CharField(blank=True, max_length=30, verbose_name='No. HP / WhatsApp'),
        ),
    ]
