# Generated by Django 6.1.1 on 2026-10-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasien', '0009_pasien_agama_pasien_alamat_pj_pasien_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunjunganpasien',
            name='cara_datang',
            field=models.CharField(blank=True, choices=[('SENDIRI', 'Sendiri / Keluarga'), ('RUJUKAN', 'Rujukan (RS / Puskesmas / Klinik)'), ('AMBULANS', 'Ambulans'), ('POLISI', 'Polisi')], max_length=15, verbose_name='Cara Datang'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='disposisi_kondisi_akhir',
            field=models.CharField(blank=True, choices=[('MEMBAIK', 'Membaik'), ('STABIL', 'Stabil'), ('MEMBURUK', 'Memburuk'), ('MENINGGAL', 'Meninggal (DOA / Di IGD)')], max_length=15, verbose_name='Kondisi Akhir IGD'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='disposisi_kontrol_poli',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kontrol Poli (Rawat Jalan)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='disposisi_kontrol_tgl',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tanggal Kontrol'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='disposisi_ruang_rawat',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ruang Rawat Inap / DPJP'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='disposisi_rujuk_alasan',
            field=models.TextField(blank=True, verbose_name='Alasan Rujukan'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='disposisi_rujuk_rs',
            field=models.CharField(blank=True, max_length=200, verbose_name='RS Tujuan Rujukan'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='disposisi_tindak_lanjut',
            field=models.CharField(blank=True, choices=[('RAWAT_INAP', 'Rawat Inap'), ('RAWAT_JALAN', 'Rawat Jalan / Pulang'), ('RUJUK', 'Rujuk ke RS Lain'), ('PAPS', 'Pulang Atas Permintaan Sendiri (PAPS)')], max_length=15, verbose_name='Tindak Lanjut Disposisi'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='gcs_e',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GCS E (Eyes)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='gcs_m',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GCS M (Motor)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='gcs_v',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='GCS V (Verbal)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='hambatan_komunikasi',
            field=models.CharField(blank=True, max_length=60, verbose_name='Hambatan Komunikasi'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='kebutuhan_spiritual',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kebutuhan Edukasi / Spiritual'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='metode_risiko_jatuh',
            field=models.CharField(blank=True, help_text='Morse Fall Scale / Humpty Dumpty / Get Up and Go', max_length=30, verbose_name='Metode Skrining Risiko Jatuh'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='nadi_irama',
            field=models.CharField(blank=True, help_text='Reguler / Ireguler', max_length=15, verbose_name='Irama Nadi'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='nadi_kekuatan',
            field=models.CharField(blank=True, help_text='Kuat / Lemah', max_length=15, verbose_name='Kekuatan Nadi'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='penunjang_ekg',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hasil EKG'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='penunjang_hasil_kritis',
            field=models.TextField(blank=True, verbose_name='Hasil Kritis Penunjang'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='penunjang_radiologi_checklist',
            field=models.JSONField(blank=True, default=list, verbose_name='Radiologi Checklist (Thorax, CT, USG, X-Ray ...)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='pernapasan_pola',
            field=models.CharField(blank=True, help_text='Spontan / Adekuat / Takipnea', max_length=20, verbose_name='Pola Pernapasan'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='petugas_handover_dokter',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nama Dokter IGD / DPJP'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='petugas_handover_dokter_jam',
            field=models.CharField(blank=True, max_length=10, verbose_name='Jam TTD Dokter IGD'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='petugas_handover_jam',
            field=models.CharField(blank=True, max_length=10, verbose_name='Jam Handover Perawat'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='petugas_handover_perawat',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nama Perawat Handover'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='rpd_checklist',
            field=models.JSONField(blank=True, default=list, verbose_name='RPD Checklist (HT, DM, Asma, Jantung, ...)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='sbar_assessment',
            field=models.TextField(blank=True, verbose_name='SBAR — Assessment'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='sbar_background',
            field=models.TextField(blank=True, verbose_name='SBAR — Background'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='sbar_recommendation',
            field=models.TextField(blank=True, verbose_name='SBAR — Recommendation'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='sbar_situation',
            field=models.TextField(blank=True, verbose_name='SBAR — Situation'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='secondary_survey_detail',
            field=models.JSONField(blank=True, default=dict, verbose_name='Secondary Survey Detail (Mata, THT, Kepala-Leher, Thorax, Abdomen, Ekstremitas)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='skala_nyeri_sifat',
            field=models.CharField(blank=True, help_text='Akut / Kronis / Hilang Timbul / Menusuk / Panas', max_length=30, verbose_name='Sifat Nyeri'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='spo2_alat',
            field=models.CharField(blank=True, help_text='Udara Bebas / Nasal Kanul / NRM', max_length=30, verbose_name='SpO2 via Alat'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='status_emosional',
            field=models.CharField(blank=True, help_text='Kooperatif / Cemas / Agresif / Depresi', max_length=30, verbose_name='Status Emosional'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='suhu_lokasi',
            field=models.CharField(blank=True, help_text='Aksila / Oral / Rectal', max_length=20, verbose_name='Lokasi Pengukuran Suhu'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='tatalaksana_resusitasi',
            field=models.TextField(blank=True, verbose_name='Resusitasi / Stabilisasi'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='tatalaksana_terapi',
            field=models.TextField(blank=True, verbose_name='Terapi Farmakologi IGD'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='tatalaksana_tindakan_check',
            field=models.JSONField(blank=True, default=list, verbose_name='Tindakan Medis IGD (Checklist)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='triase_kategori',
            field=models.CharField(blank=True, choices=[('KATEGORI_1', 'Kategori 1 (Resusitasi / Merah) — Immediate'), ('KATEGORI_2', 'Kategori 2 (Emergensi / Merah) — 10 menit'), ('KATEGORI_3', 'Kategori 3 (Urgensi / Kuning) — 30 menit'), ('KATEGORI_4', 'Kategori 4 (Non-Urgensi / Hijau) — 60 menit'), ('KATEGORI_5', 'Kategori 5 (Rutin / Hitam / DOA) — 120 menit')], max_length=15, verbose_name='Triase Kategori (ATS/ESI)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='waktu_asesmen_dokter',
            field=models.CharField(blank=True, max_length=10, verbose_name='Waktu Asesmen Dokter (WIB)'),
        ),
        migrations.AddField(
            model_name='kunjunganpasien',
            name='waktu_disposisi',
            field=models.CharField(blank=True, max_length=10, verbose_name='Waktu Keputusan Disposisi (WIB)'),
        ),
        migrations.AddField(
            model_name='orderpenunjang',
            name='kondisi_sampel',
            field=models.CharField(blank=True, help_text='Puasa / Tidak Puasa / Hamil', max_length=30, verbose_name='Kondisi Sampel'),
        ),
        migrations.AddField(
            model_name='orderpenunjang',
            name='parameter_list',
            field=models.JSONField(blank=True, default=list, verbose_name='Daftar Parameter Pemeriksaan'),
        ),
    ]
