# Generated by Django 6.1 on 2026-09-11 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('R', 'R — Regulasi (SK, Pedoman, SPO)'), ('D', 'D — Dokumen / Bukti Fisik (Laporan, Notulen)'), ('W', 'W — Wawancara'), ('O', 'O — Observasi Lapangan'), ('S', 'S — Simulasi')], max_length=2, verbose_name='Kategori Bukti')),
                ('title', models.CharField(max_length=300, verbose_name='Kebutuhan Pembuktian yang Diunggah')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Wajib Dilengkapi')),
            ],
            options={
                'verbose_name': 'Kebutuhan Bukti (RDWOS)',
                'verbose_name_plural': 'Kebutuhan Bukti (RDWOS)',
                'ordering': ['category_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Standar')),
                ('cycle_type', models.CharField(default='PDCA', max_length=20, verbose_name='Siklus Kendali Mutu')),
                ('version', models.CharField(default='2026', max_length=50, verbose_name='Versi / Edisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Standar Akreditasi',
                'verbose_name_plural': 'Standar Akreditasi',
            },
        ),
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nama Unit Kerja')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kode Unit')),
                ('pic_name', models.CharField(blank=True, max_length=150, verbose_name='Penanggung Jawab (PIC)')),
            ],
            options={
                'verbose_name': 'Unit Kerja',
                'verbose_name_plural': 'Unit Kerja',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('CREATE', 'Tambah'), ('UPDATE', 'Ubah'), ('DELETE', 'Hapus'), ('SCORE', 'Ubah Skor'), ('UPLOAD', 'Unggah Berkas')], max_length=15)),
                ('model_name', models.CharField(max_length=50)),
                ('object_repr', models.CharField(max_length=250)),
                ('detail', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Audit',
                'verbose_name_plural': 'Log Audit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='bukti/%Y/%m/', verbose_name='File Bukti')),
                ('file_url', models.URLField(blank=True, max_length=500, verbose_name='URL Cloud Storage (Supabase)')),
                ('file_name', models.CharField(max_length=250, verbose_name='Nama Berkas')),
                ('file_size', models.CharField(default='1.2 MB', max_length=50, verbose_name='Ukuran Berkas')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versi')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review Ketua Pokja'), ('VALID', 'Valid / Disetujui Tim Mutu')], default='VALID', max_length=20, verbose_name='Status Keabsahan')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='akreditasi.evidencereq')),
            ],
            options={
                'verbose_name': 'Berkas Bukti',
                'verbose_name_plural': 'Berkas Bukti',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Kode Pokja')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Pokja')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='akreditasi.framework')),
            ],
            options={
                'verbose_name': 'Kelompok Kerja (Pokja)',
                'verbose_name_plural': 'Kelompok Kerja (Pokja)',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StandardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_standard', models.CharField(max_length=50, verbose_name='Sub-Standar')),
                ('sub_title', models.CharField(max_length=250, verbose_name='Judul Sub-Standar')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode Elemen Penilaian (EP)')),
                ('description', models.TextField(verbose_name='Bunyi Standar / Elemen Penilaian')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='akreditasi.category')),
            ],
            options={
                'verbose_name': 'Elemen Penilaian (EP)',
                'verbose_name_plural': 'Elemen Penilaian (EP)',
                'ordering': ['category__order', 'order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='evidencereq',
            name='standard_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_reqs', to='akreditasi.standarditem'),
        ),
        migrations.CreateModel(
            name='QualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_data', models.TextField(blank=True, verbose_name='Asesmen / Kondisi Riil Saat Ini (Baseline)')),
                ('quality_target', models.CharField(blank=True, max_length=300, verbose_name='Indikator Capaian Mutu (INM/IMP/IMU)')),
                ('risk_mitigation', models.TextField(blank=True, verbose_name='Rencana Mitigasi Risiko (Risk Register)')),
                ('score', models.PositiveSmallIntegerField(choices=[(10, '10 — Lengkap (≥80%)'), (5, '5 — Sebagian (20-79%)'), (0, '0 — Belum Terpenuhi (<20%)')], default=0, verbose_name='Nilai / Skor Self-Assessment')),
                ('eval_notes', models.TextField(blank=True, verbose_name='Catatan Evaluasi / Rekomendasi Asesor')),
                ('action_plan', models.TextField(blank=True, verbose_name='Rencana Tindak Lanjut (Action Plan)')),
                ('pic', models.CharField(blank=True, max_length=150, verbose_name='Penanggung Jawab (PIC)')),
                ('target_date', models.CharField(blank=True, max_length=100, verbose_name='Target Waktu Penyelesaian')),
                ('est_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Estimasi Biaya (Rp)')),
                ('budget_source', models.CharField(blank=True, max_length=150, verbose_name='Sumber Alokasi Anggaran')),
                ('budget_status', models.CharField(choices=[('APPROVED', 'Disetujui (RKA)'), ('SUBMITTED', 'Dalam Pengajuan'), ('NON_BUDGET', 'Non-Biaya (Rp 0)'), ('DRAFT', 'Draft')], default='DRAFT', max_length=20, verbose_name='Status Anggaran')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='akreditasi.standarditem')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='akreditasi.unitkerja')),
            ],
            options={
                'verbose_name': 'Record Siklus PDCA',
                'verbose_name_plural': 'Record Siklus PDCA',
            },
        ),
    ]
