# Generated by Django 6.1 on 2026-09-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RumahSakitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rumah Sakit Umum', max_length=300, verbose_name='Nama Rumah Sakit')),
                ('kode_rs', models.CharField(blank=True, max_length=50, verbose_name='Kode RS')),
                ('alamat', models.TextField(blank=True, verbose_name='Alamat')),
                ('kota', models.CharField(blank=True, max_length=100, verbose_name='Kota')),
                ('telepon', models.CharField(blank=True, max_length=50, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('direktur', models.CharField(blank=True, max_length=200, verbose_name='Nama Direktur')),
                ('tipe', models.CharField(blank=True, help_text='Contoh: RS Tipe B, RSUD, RSKIA', max_length=100, verbose_name='Tipe RS')),
                ('akreditasi_tahun', models.PositiveIntegerField(default=2026, verbose_name='Tahun Target Akreditasi')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL Logo RS')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Rumah Sakit',
                'verbose_name_plural': 'Profil Rumah Sakit',
            },
        ),
    ]
