# Generated by Django 6.1 on 2026-09-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0002_rumahsakitprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitkerja',
            options={'ordering': ['level', 'code'], 'verbose_name': 'Unit Kerja', 'verbose_name_plural': 'Unit Kerja'},
        ),
        migrations.AddField(
            model_name='unitkerja',
            name='description',
            field=models.TextField(blank=True, verbose_name='Keterangan / Fungsi'),
        ),
        migrations.AddField(
            model_name='unitkerja',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tingkat 1 — Direktorat / Bidang'), (2, 'Tingkat 2 — Bagian / Instalasi / Komite'), (3, 'Tingkat 3 — Sub-Bagian / Ruangan / Unit Layanan')], default=1, verbose_name='Tingkat Hierarki'),
        ),
        migrations.AddField(
            model_name='unitkerja',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='akreditasi.unitkerja', verbose_name='Induk Unit Kerja'),
        ),
        migrations.AlterField(
            model_name='unitkerja',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nama Unit Kerja'),
        ),
    ]
