# Generated by Django 5.2.17 on 2026-09-25 00:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0003_alter_unitkerja_options_unitkerja_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndikatorMutu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_indikator', models.CharField(max_length=300, verbose_name='Nama Indikator')),
                ('kode_indikator', models.CharField(max_length=50, unique=True, verbose_name='Kode Indikator')),
                ('jenis', models.CharField(choices=[('IMP_RS', 'IMP Rumah Sakit'), ('IMP_UNIT', 'IMP Unit'), ('NASIONAL', 'Indikator Nasional Mutu'), ('SNI', 'Standar Nasional Indonesia')], max_length=10, verbose_name='Jenis Indikator')),
                ('dimensi_mutu', models.CharField(choices=[('EFEKTIF', 'Efektif'), ('EFISIEN', 'Efisien'), ('AKSESIBEL', 'Aksesibel'), ('AMAN', 'Aman'), ('BERPUSAT_PASIEN', 'Berpusat pada Pasien'), ('TEPAT_WAKTU', 'Tepat Waktu'), ('ADIL', 'Adil')], max_length=20, verbose_name='Dimensi Mutu')),
                ('numerator', models.CharField(max_length=300, verbose_name='Numerator')),
                ('denominator', models.CharField(max_length=300, verbose_name='Denominator')),
                ('target_nilai', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Target Nilai')),
                ('satuan', models.CharField(default='%', max_length=20, verbose_name='Satuan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('ep_terkait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indikator_mutu', to='akreditasi.standarditem', verbose_name='EP Terkait')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akreditasi.unitkerja', verbose_name='Unit Kerja')),
            ],
            options={
                'verbose_name': 'Indikator Mutu',
                'verbose_name_plural': 'Indikator Mutu',
                'ordering': ['jenis', 'kode_indikator'],
            },
        ),
        migrations.CreateModel(
            name='InsidenKeselamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kejadian', models.DateField(verbose_name='Tanggal Kejadian')),
                ('waktu_kejadian', models.TimeField(blank=True, null=True, verbose_name='Waktu Kejadian')),
                ('jenis_insiden', models.CharField(choices=[('KNC', 'KNC — Kejadian Nyaris Cedera'), ('KTD', 'KTD — Kejadian Tidak Diharapkan'), ('KTC', 'KTC — Kejadian Tidak Cedera'), ('SENTINEL', 'Kejadian Sentinel'), ('KEJADIAN_LAIN', 'Kejadian Lain')], max_length=15, verbose_name='Jenis Insiden')),
                ('tingkat_keparahan', models.CharField(choices=[('TIDAK_CEDERA', 'Tidak Cedera'), ('MINOR', 'Minor'), ('MODERAT', 'Moderat'), ('MAYOR', 'Mayor'), ('SENTINEL', 'Sentinel')], max_length=15, verbose_name='Tingkat Keparahan')),
                ('lokasi_kejadian', models.CharField(max_length=200, verbose_name='Lokasi Kejadian')),
                ('deskripsi_kejadian', models.TextField(verbose_name='Deskripsi Kejadian')),
                ('tindakan_segera', models.TextField(blank=True, verbose_name='Tindakan Segera')),
                ('pasien_terpapar', models.BooleanField(default=False, verbose_name='Pasien Terpapar')),
                ('pelapor_anonim', models.BooleanField(default=True, verbose_name='Pelapor Anonim')),
                ('status_investigasi', models.CharField(choices=[('DILAPORKAN', 'Dilaporkan'), ('VERIFIKASI', 'Verifikasi'), ('INVESTIGASI', 'Investigasi'), ('SELESAI', 'Selesai')], default='DILAPORKAN', max_length=12, verbose_name='Status Investigasi')),
                ('rca_dilakukan', models.BooleanField(default=False, verbose_name='RCA Dilakukan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pj_investigasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insiden_investigasi', to=settings.AUTH_USER_MODEL, verbose_name='PJ Investigasi')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akreditasi.unitkerja', verbose_name='Unit Terkait')),
            ],
            options={
                'verbose_name': 'Insiden Keselamatan',
                'verbose_name_plural': 'Insiden Keselamatan',
                'ordering': ['-tanggal_kejadian'],
            },
        ),
        migrations.CreateModel(
            name='RisikoUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(default=2026, verbose_name='Tahun')),
                ('periode', models.CharField(choices=[('TRIWULAN_1', 'Triwulan I (Jan–Mar)'), ('TRIWULAN_2', 'Triwulan II (Apr–Jun)'), ('TRIWULAN_3', 'Triwulan III (Jul–Sep)'), ('TRIWULAN_4', 'Triwulan IV (Okt–Des)'), ('TAHUNAN', 'Tahunan')], max_length=12, verbose_name='Periode')),
                ('kategori_risiko', models.CharField(choices=[('KLINIS', 'Risiko Klinis'), ('MANAJERIAL', 'Risiko Manajerial')], max_length=12, verbose_name='Kategori Risiko')),
                ('jenis_risiko', models.CharField(max_length=200, verbose_name='Jenis Risiko')),
                ('deskripsi_risiko', models.TextField(verbose_name='Deskripsi Risiko')),
                ('dampak', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Dampak (1–5)')),
                ('probabilitas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Probabilitas (1–5)')),
                ('strategi_mitigasi', models.CharField(choices=[('HINDARI', 'Hindari (Avoid)'), ('KURANGI', 'Kurangi (Reduce)'), ('TRANSFER', 'Transfer'), ('TERIMA', 'Terima (Accept)')], max_length=10, verbose_name='Strategi Mitigasi')),
                ('rencana_aksi', models.TextField(verbose_name='Rencana Aksi')),
                ('pj_mitigasi', models.CharField(max_length=150, verbose_name='PJ Mitigasi')),
                ('target_selesai', models.DateField(blank=True, null=True, verbose_name='Target Selesai')),
                ('bukti_pelaksanaan', models.TextField(blank=True, verbose_name='Bukti Pelaksanaan')),
                ('dampak_residual', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Dampak Residual (1–5)')),
                ('probabilitas_residual', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Probabilitas Residual (1–5)')),
                ('status', models.CharField(choices=[('IDENTIFIKASI', 'Identifikasi'), ('PLAN', 'Plan'), ('DO', 'Do'), ('EVALUASI', 'Evaluasi/Check'), ('SELESAI', 'Selesai/Act'), ('ACCEPTED', 'Diterima (Accepted Risk)')], default='IDENTIFIKASI', max_length=12, verbose_name='Status PDCA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risiko_dibuat', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akreditasi.unitkerja', verbose_name='Unit Kerja')),
            ],
            options={
                'verbose_name': 'Risiko Unit',
                'verbose_name_plural': 'Risiko Unit',
                'ordering': ['-tahun', 'periode'],
            },
        ),
        migrations.CreateModel(
            name='TindakLanjutRisiko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.IntegerField(verbose_name='Urutan Aksi')),
                ('aksi', models.CharField(max_length=500, verbose_name='Aksi')),
                ('status_aksi', models.CharField(choices=[('BELUM', 'Belum Dimulai'), ('SEDANG', 'Sedang Berjalan'), ('SELESAI', 'Selesai')], default='BELUM', max_length=10, verbose_name='Status Aksi')),
                ('tanggal_mulai', models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('bukti_upload', models.FileField(blank=True, null=True, upload_to='risiko/bukti/', verbose_name='Bukti Upload')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('risiko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tindak_lanjut', to='akreditasi.risikounit')),
            ],
            options={
                'verbose_name': 'Tindak Lanjut Risiko',
                'verbose_name_plural': 'Tindak Lanjut Risiko',
                'ordering': ['risiko', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='CatatanIndikator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Bulan')),
                ('tahun', models.IntegerField(default=2026, verbose_name='Tahun')),
                ('nilai_numerator', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nilai Numerator')),
                ('nilai_denominator', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nilai Denominator')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan', to='akreditasi.indikatormutu')),
            ],
            options={
                'verbose_name': 'Catatan Indikator',
                'verbose_name_plural': 'Catatan Indikator',
                'ordering': ['-tahun', '-bulan'],
                'unique_together': {('indikator', 'bulan', 'tahun')},
            },
        ),
    ]
