# Generated by Django 5.2.17 on 2026-09-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0005_update_rs_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_paripurna', models.PositiveSmallIntegerField(default=80, verbose_name='Minimal Paripurna (%)')),
                ('threshold_utama', models.PositiveSmallIntegerField(default=70, verbose_name='Minimal Utama (%)')),
                ('threshold_madya', models.PositiveSmallIntegerField(default=60, verbose_name='Minimal Madya (%)')),
                ('threshold_dasar', models.PositiveSmallIntegerField(default=20, verbose_name='Minimal Dasar (%)')),
                ('survey_freeze_mode', models.BooleanField(default=False, help_text='Saat aktif, hanya Super Admin yang bisa mengedit. Seluruh staf & pokja beralih ke Mode Baca Saja.', verbose_name='Mode Kunci Survei (Read-Only Freeze)')),
                ('survey_freeze_message', models.CharField(default='Sistem sedang dalam Mode Survei Akreditasi Lapangan. Penambahan/perubahan dokumen dinonaktifkan sementara.', max_length=255, verbose_name='Pesan Banner Mode Survei')),
                ('kps_alert_days', models.PositiveIntegerField(default=90, verbose_name='Peringatan Expired STR/SIP (Hari)')),
                ('allow_nakes_self_upload', models.BooleanField(default=True, verbose_name='Izinkan Nakes Unggah Dokumen Mandiri')),
                ('max_upload_size_mb', models.PositiveIntegerField(default=15, verbose_name='Batas Maksimal Berkas (MB)')),
                ('allowed_extensions', models.CharField(default='pdf,docx,xlsx,jpg,png,jpeg', max_length=150, verbose_name='Ekstensi Berkas Diizinkan')),
                ('risk_threshold_sangat_tinggi', models.PositiveSmallIntegerField(default=20, verbose_name='Skor Sangat Tinggi (Merah)')),
                ('risk_threshold_tinggi', models.PositiveSmallIntegerField(default=15, verbose_name='Skor Tinggi (Oranye)')),
                ('risk_threshold_sedang', models.PositiveSmallIntegerField(default=10, verbose_name='Skor Sedang (Kuning)')),
                ('risk_threshold_rendah', models.PositiveSmallIntegerField(default=5, verbose_name='Skor Rendah (Hijau)')),
                ('theme_color', models.CharField(choices=[('teal', 'Teal Medis (Default RS MonsisKami)'), ('blue', 'Hospital Royal Blue'), ('emerald', 'Emerald Green Health'), ('navy', 'Dark Navy Slate')], default='teal', max_length=20, verbose_name='Warna Tema Sistem')),
                ('kop_surat_text', models.TextField(blank=True, default='PEMERINTAH DAERAH / YAYASAN KESEHATAN\nRS MONSISKAMI (TIPE B)\nJl. Kesehatan No. 1, Jakarta', verbose_name='Teks Kop Surat Resmi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi Sistem',
                'verbose_name_plural': 'Konfigurasi Sistem',
            },
        ),
        migrations.AlterModelOptions(
            name='unitkerja',
            options={'ordering': ['level', 'order', 'code'], 'verbose_name': 'Unit Kerja', 'verbose_name_plural': 'Unit Kerja'},
        ),
        migrations.AddField(
            model_name='unitkerja',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Nonaktifkan unit tanpa menghapus data akreditasi historis.', verbose_name='Unit Aktif'),
        ),
        migrations.AddField(
            model_name='unitkerja',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Urutan Tampilan'),
        ),
        migrations.AddField(
            model_name='unitkerja',
            name='tipe_unit',
            field=models.CharField(blank=True, choices=[('PIMPINAN', 'Pimpinan / Pemilik / Dewas'), ('DIREKTORAT', 'Direktorat / Bidang'), ('KOMITE', 'Komite Medis / Keperawatan / Mutu'), ('SPI', 'Satuan Pengawas Internal'), ('BAGIAN', 'Bagian / Sub-Bagian Administrasi'), ('INSTALASI', 'Instalasi Pelayanan Medis / Penunjang'), ('KSM', 'Kelompok Staf Medis (KSM Spesialis)'), ('RUANGAN', 'Ruangan Perawatan / Tindakan'), ('DEPO', 'Depo Farmasi / Satelit'), ('LAINNYA', 'Unit Penunjang Lainnya')], default='LAINNYA', max_length=40, verbose_name='Jenis / Kategori Unit'),
        ),
        migrations.AlterField(
            model_name='unitkerja',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Tingkat Hierarki'),
        ),
    ]
