# Generated by Django 5.2.17 on 2026-09-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0006_systemconfig_alter_unitkerja_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='Dimulai dengan sk-... Disimpan terenkripsi, tidak pernah dikirim ke frontend.', max_length=200, verbose_name='DeepSeek API Key'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ai_enable_insiden',
            field=models.BooleanField(default=True, verbose_name='AI: Modul Laporan Insiden'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ai_enable_kps',
            field=models.BooleanField(default=True, verbose_name='AI: Modul KPS / Kredensial Nakes'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ai_enable_pdca',
            field=models.BooleanField(default=True, verbose_name='AI: Modul Matriks PDCA'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ai_enable_rdwos',
            field=models.BooleanField(default=True, verbose_name='AI: Modul Dokumen Bukti RDWOS'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ai_enable_risiko',
            field=models.BooleanField(default=True, verbose_name='AI: Modul Manajemen Risiko'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ai_enabled',
            field=models.BooleanField(default=False, verbose_name='Aktifkan Asisten AI DeepSeek'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ai_max_tokens',
            field=models.PositiveSmallIntegerField(default=1000, verbose_name='Maksimal Token Output AI'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ai_model_name',
            field=models.CharField(choices=[('deepseek-chat', 'DeepSeek-V3 Chat (Cepat & Ekonomis)'), ('deepseek-reasoner', 'DeepSeek-R1 Reasoner (Penalaran Klinis Mendalam)')], default='deepseek-chat', max_length=50, verbose_name='Model DeepSeek Default'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='ai_temperature',
            field=models.FloatField(default=0.3, verbose_name='Kreativitas AI (temperature 0.0–1.0)'),
        ),
    ]
