# Generated by Django 5.2.17 on 2026-09-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0007_add_ai_deepseek_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitkerja',
            name='standar_terkait',
            field=models.JSONField(blank=True, default=dict, help_text='Daftar Bab Pokja dan Kode Standar STARKES yang menjadi tanggung jawab unit ini, misal: {"PKPO": ["PKPO 1", "PKPO 2"]}', verbose_name='Standar Akreditasi Terkait Unit'),
        ),
    ]
