# Generated by Django 5.2.17 on 2026-09-28 03:22

from django.db import migrations


def seed_farmasi_standar(apps, schema_editor):
    UnitKerja = apps.get_model('akreditasi', 'UnitKerja')
    farm_units = UnitKerja.objects.filter(code__in=['FARM', 'FAR'])
    standar_data = {
        'TKRS': ['TKRS 9', 'TKRS 10', 'TKRS 11'],
        'PKPO': ['PKPO 1', 'PKPO 2', 'PKPO 3', 'PKPO 4', 'PKPO 5', 'PKPO 6 & 7'],
        'PPI':  ['PPI 5', 'PPI 7', 'PPI 7.1', 'PPI 7.2', 'PPI 8'],
        'MFK':  ['MFK 4', 'MFK 5', 'MFK 5.1', 'MFK 7', 'MFK 8', 'MFK 9'],
        'KPS':  ['KPS 1 & 3', 'KPS 4', 'KPS 5', 'KPS 8', 'KPS 10 & 12', 'KPS 11 & 14'],
    }
    for u in farm_units:
        u.standar_terkait = standar_data
        u.save(update_fields=['standar_terkait'])


def unseed_farmasi_standar(apps, schema_editor):
    UnitKerja = apps.get_model('akreditasi', 'UnitKerja')
    UnitKerja.objects.filter(code__in=['FARM', 'FAR']).update(standar_terkait={})


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0008_add_standar_terkait_unit'),
    ]

    operations = [
        migrations.RunPython(seed_farmasi_standar, unseed_farmasi_standar),
    ]
