# Generated by Django 5.2.17 on 2026-09-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0009_seed_farmasi_standar_terkait'),
    ]

    operations = [
        migrations.AddField(
            model_name='risikounit',
            name='biaya_mitigasi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Estimasi Biaya Mitigasi (Rp)'),
        ),
    ]
