# Generated by Django 5.2.17 on 2026-09-29 01:41

from django.core.management import call_command
from django.db import migrations


def run_seed(apps, schema_editor):
    call_command('seed_struktur_monsiskami')


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0010_add_biaya_mitigasi'),
    ]

    operations = [
        migrations.RunPython(run_seed, migrations.RunPython.noop),
    ]
