# Generated by Django 5.2.17 on 2026-09-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0011_seed_monsiskami_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kelompok',
            field=models.CharField(choices=[('MANAJEMEN', 'Kelompok Manajemen Rumah Sakit'), ('PELAYANAN', 'Kelompok Pelayanan Berfokus pada Pasien'), ('SASARAN_KP', 'Kelompok Sasaran Keselamatan Pasien'), ('PROGNAS', 'Kelompok Program Nasional'), ('PENDIDIKAN', 'Kelompok Integrasi Pendidikan Kesehatan')], default='MANAJEMEN', max_length=20, verbose_name='Kelompok Standar'),
        ),
        migrations.AddField(
            model_name='category',
            name='target_ep_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Target Jumlah EP STARKES'),
        ),
        migrations.AddField(
            model_name='category',
            name='unit_pengampu',
            field=models.TextField(blank=True, verbose_name='Unit Pengampu & Terlibat'),
        ),
    ]
