# Generated by Django 5.2.17 on 2026-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0024_seed_demo_readonly_and_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumahsakitprofile',
            name='misi',
            field=models.TextField(blank=True, help_text='Pisahkan tiap poin misi dengan baris baru', verbose_name='Misi Rumah Sakit'),
        ),
        migrations.AddField(
            model_name='rumahsakitprofile',
            name='motto',
            field=models.CharField(blank=True, max_length=300, verbose_name='Motto / Tagline RS'),
        ),
        migrations.AddField(
            model_name='rumahsakitprofile',
            name='tujuan',
            field=models.TextField(blank=True, help_text='Tujuan umum RS jangka panjang', verbose_name='Tujuan Strategis'),
        ),
        migrations.AddField(
            model_name='rumahsakitprofile',
            name='visi',
            field=models.TextField(blank=True, verbose_name='Visi Rumah Sakit'),
        ),
    ]
