# Generated by Django 5.2.17 on 2026-10-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0025_add_visi_misi_tujuan_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='risikounit',
            name='indikator_mutu_terkait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risiko_terkait', to='akreditasi.indikatormutu', verbose_name='Indikator Mutu Terkait'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='target_capaian_indikator',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Target Capaian Indikator (%)'),
        ),
    ]
