# Generated by Django 5.2.17 on 2026-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0026_risikounit_indikator_mutu_terkait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indikatormutu',
            name='pj',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Penanggung Jawab'),
        ),
        migrations.AddField(
            model_name='indikatormutu',
            name='rencana_aksi',
            field=models.TextField(blank=True, default='', verbose_name='Rencana Aksi (Preset)'),
        ),
    ]
