# Generated by Django 5.2.17 on 2026-10-04 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0027_indikatormutu_pj_indikatormutu_rencana_aksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenstraRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Tahun Renstra')),
                ('isu_strategis', models.CharField(max_length=200, verbose_name='Isu Strategis')),
                ('sub_tema', models.CharField(blank=True, max_length=250, verbose_name='Sub-Tema / Fokus Utama')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi Rencana Strategis')),
                ('ikon', models.CharField(default='bi-flag', help_text='Contoh: bi-cpu, bi-gear-wide-connected, bi-hospital, bi-tree, bi-trophy', max_length=50, verbose_name='Class Bootstrap Icon')),
                ('warna_hex', models.CharField(default='#0d6efd', help_text='Contoh: #0d6efd, #6f42c1, #198754, #20c997, #fd7e14', max_length=20, verbose_name='Kode Warna Hex')),
                ('urutan', models.PositiveSmallIntegerField(default=1, verbose_name='Urutan Tampil')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif Ditampilkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Roadmap Renstra Tahunan',
                'verbose_name_plural': 'Roadmap Renstra RS (2026–2030)',
                'ordering': ['urutan', 'tahun'],
            },
        ),
        migrations.CreateModel(
            name='RenstraFokusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.PositiveSmallIntegerField(default=1, verbose_name='Nomor Urut Fokus')),
                ('nama_fokus', models.CharField(max_length=255, verbose_name='Nama Indikator / Program Fokus')),
                ('kode_ref', models.CharField(blank=True, help_text='Contoh: IMP-RM-01, INM-08', max_length=50, verbose_name='Kode Ref Cadangan')),
                ('target_label', models.CharField(default='100%', max_length=100, verbose_name='Target Label Teks')),
                ('target_nilai', models.DecimalField(decimal_places=2, default=100.0, max_digits=8, verbose_name='Nilai Target Numerik')),
                ('satuan', models.CharField(default='%', max_length=30, verbose_name='Satuan')),
                ('unit_kerja_label', models.CharField(blank=True, max_length=150, verbose_name='Unit Kerja Penanggung Jawab')),
                ('indikator_mutu', models.ForeignKey(blank=True, help_text='Tautkan ke Master Indikator Mutu (opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renstra_fokus', to='akreditasi.indikatormutu')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fokus_items', to='akreditasi.renstraroadmap')),
            ],
            options={
                'verbose_name': 'Butir Fokus Indikator Renstra',
                'verbose_name_plural': 'Butir Fokus Indikator Renstra',
                'ordering': ['nomor'],
            },
        ),
    ]
