# Generated by Django 6.1.1 on 2026-10-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0028_create_renstra_roadmap_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='risikounit',
            name='data_pendukung',
            field=models.TextField(blank=True, default='', verbose_name='Data / Bukti Pendukung'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='masalah',
            field=models.TextField(blank=True, default='', verbose_name='Masalah'),
        ),
        migrations.AlterField(
            model_name='risikounit',
            name='kategori_risiko',
            field=models.CharField(choices=[('KLINIS', 'Risiko Klinis (Clinical Risk)'), ('OPERASIONAL', 'Risiko Operasional (Operational Risk)'), ('FINANSIAL', 'Risiko Finansial (Financial Risk)'), ('REPUTASI', 'Risiko Reputasi (Reputational Risk)'), ('HUKUM_KEPATUHAN', 'Risiko Hukum & Kepatuhan (Legal & Compliance)'), ('FASILITAS_LINGKUNGAN', 'Risiko Fasilitas, B3 & Lingkungan (Facility & Env.)'), ('MANAJERIAL', 'Risiko Manajerial (Legacy)')], max_length=30, verbose_name='Kategori Risiko'),
        ),
    ]
