# Generated by Django 6.1.1 on 2026-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0029_risikounit_data_pendukung_risikounit_masalah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risikounit',
            name='jenis_risiko',
            field=models.TextField(verbose_name='Jenis Risiko'),
        ),
    ]
