# Generated by Django 6.1.1 on 2026-10-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0030_alter_risikounit_jenis_risiko'),
    ]

    operations = [
        migrations.AddField(
            model_name='risikounit',
            name='akar_masalah_rca',
            field=models.TextField(blank=True, default='', verbose_name='Analisis Akar Masalah (RCA 5-Whys / Fishbone)'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='failure_mode_fmea',
            field=models.TextField(blank=True, default='', verbose_name='Mode Kegagalan & Efek Potensial (FMEA)'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='metode_evaluasi',
            field=models.CharField(choices=[('STANDAR', 'Standar Pemantauan PDCA'), ('FMEA', 'FMEA — Failure Mode and Effects Analysis (Proaktif)'), ('RCA', 'RCA — Root Cause Analysis (Reaktif)')], default='STANDAR', help_text='Standar PDCA, FMEA (proaktif), atau RCA (reaktif).', max_length=10, verbose_name='Metode Evaluasi Mendalam'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='rpn_fmea',
            field=models.IntegerField(blank=True, null=True, verbose_name='RPN — Risk Priority Number (FMEA)'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='tanggal_evaluasi',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Evaluasi / Investigasi'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='tim_evaluasi',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tim Evaluasi / Investigasi'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='tindakan_korektif_rca',
            field=models.TextField(blank=True, default='', verbose_name='Rencana Tindakan Korektif & Solusi Permanen'),
        ),
    ]
