# Generated by Django 6.1.1 on 2026-10-10 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akreditasi', '0031_add_fmea_rca_to_risikounit'),
    ]

    operations = [
        migrations.AddField(
            model_name='risikounit',
            name='deteksi_fmea',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Tingkat Deteksi / Detection (1–5)'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='deteksi_residual',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Deteksi Residu (1–5)'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='evaluasi_capaian',
            field=models.TextField(blank=True, default='', verbose_name='Evaluasi Capaian Indikator Mutu'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='pengendalian_ada',
            field=models.TextField(blank=True, default='', verbose_name='Pengendalian yang Sudah Ada (Existing Control)'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='pj_rtl',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='PJ Tindak Lanjut (RTL)'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='rca_ulang',
            field=models.TextField(blank=True, default='', verbose_name='RCA Ulang / Investigasi Lanjutan'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='rencana_tindak_lanjut',
            field=models.TextField(blank=True, default='', verbose_name='Rencana Tindak Lanjut (RTL)'),
        ),
        migrations.AddField(
            model_name='risikounit',
            name='rpn_residual',
            field=models.IntegerField(blank=True, null=True, verbose_name='RPN Residu (FMEA)'),
        ),
    ]
